# Generated by Django 5.2.4 on 2025-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
