# Generated by Django 5.2.4 on 2025-09-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permit',
            options={'managed': False},
        ),
    ]
