# Generated by Django 5.2.4 on 2025-09-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_alter_permit_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permit',
            table='GISPermits',
        ),
    ]
