# Generated by Django 5.0.7 on 2025-10-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaPurchasesQ',
            fields=[
                ('NEW_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('adaid', models.CharField(blank=True, max_length=255, null=True)),
                ('bkqty', models.IntegerField(blank=True, null=True)),
                ('chknum', models.CharField(blank=True, max_length=255, null=True)),
                ('deptenter', models.CharField(blank=True, max_length=255, null=True)),
                ('ehid', models.CharField(blank=True, max_length=255, null=True)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('inpermail', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('maildate', models.DateTimeField(blank=True, null=True)),
                ('old_transid', models.CharField(blank=True, max_length=255, null=True)),
                ('paytype', models.CharField(blank=True, max_length=255, null=True)),
                ('puramt', models.IntegerField(blank=True, null=True)),
                ('purdate', models.DateTimeField(blank=True, null=True)),
                ('TransID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ADA_Purchases_q',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdaRiderQ',
            fields=[
                ('NEW_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('adaid', models.CharField(blank=True, max_length=255, null=True)),
                ('ADD1', models.CharField(blank=True, max_length=255, null=True)),
                ('aptstname', models.CharField(blank=True, max_length=255, null=True)),
                ('aptstnum', models.CharField(blank=True, max_length=50, null=True)),
                ('aptunit', models.CharField(blank=True, max_length=50, null=True)),
                ('ehid', models.CharField(blank=True, max_length=255, null=True)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('Inactive', models.BooleanField(default=False)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('missaddr', models.CharField(blank=True, max_length=255, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('RDRN', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ADA_Riders_q',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdaTicketPurchasesT',
            fields=[
                ('NEW_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('bkqty', models.IntegerField(blank=True, null=True)),
                ('chknum', models.CharField(blank=True, max_length=255, null=True)),
                ('deptenter', models.CharField(blank=True, max_length=255, null=True)),
                ('ehid', models.CharField(blank=True, max_length=255, null=True)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('inpermail', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('maildate', models.DateTimeField(blank=True, null=True)),
                ('old_transid', models.CharField(blank=True, max_length=255, null=True)),
                ('paytype', models.CharField(blank=True, max_length=255, null=True)),
                ('puramt', models.IntegerField(blank=True, null=True)),
                ('purdate', models.DateTimeField(blank=True, null=True)),
                ('TransID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ADA_Ticket_Purchases_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trans_id', models.IntegerField(db_index=True)),
                ('rider_new_id', models.IntegerField(blank=True, null=True)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('lname', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('deptenter', models.CharField(blank=True, max_length=255, null=True)),
                ('paytype', models.CharField(blank=True, max_length=255, null=True)),
                ('chknum', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TicketAudit',
                'managed': True,
            },
        ),
    ]
